### ISSUE TITLE
Inequality constraints notebook fails for a random seed 1793

### ISSUE THREAD

**Issue by apaleyes** [secondmind-labs/trieste#437] opened 2021-11-25 11:50 UTC
**Describe the bug**
When running inequality constraints notebook with random seed 1793, several people reported failures. It can also be seen in the github build: https://github.com/secondmind-labs/trieste/runs/4309808577

**To reproduce**
Steps to reproduce the behaviour:
1. Clone and install Trieste from sources
2. Go to doc/notebooks/
3. Change random seed in `inequality_constraints.pct.py` to 1793, if not already set to it.
4. Run `python inequality_constraints.pct.py`. Don't forget to close matplotlib images when they appear!
5. Observe following error:
```
FailedOptimizationError: 
                    Acquisition function optimization failed,
                    even after 6 restarts.
```

**Expected behaviour**
The notebook completes without errors.

**System information**
 - OS: ...
 - Python version: 3.7.5
 - Trieste version: 0.8.0
 - TensorFlow version: 2.5

**Additional context**
The build error is now fixed by switching to a different random seed: #435. However the question on why the notebook fails for a certain random seed remains open.

**Comment by uri-granta** [comment] 2023-06-29 12:06
I've tried but failed to reproduce this in the current version (unsurprisingly due to the various changes that have happened since and the fact that this wasn't being hit often). Suggest closing as unreproducible for now though we'll keep an eye out for it in future.

**Closed as completed by uri-granta** 2023-06-29 12:06 UTC
Labels: bug
